In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
raw_path = "/home/schaffen/Workspace/Project/Lead_classification/data/data/raw/demo.csv"

In [3]:

df = pd.read_csv(raw_path)
df.head()

,lien_he,tu_van,bao_gia,demo,qtam,qd,tg,age,size,role,channel,web_time,frac_react,frac_cmt,avg_res,target
0,0,0,0,0,1,1,0,52,Micro,Manager,FB,290.5,0.141,0.007,2228,Warm
1,1,1,0,0,1,1,0,52,Medium,Marketing,FB,287.9,0.198,0.013,3712,Warm
2,1,0,0,0,1,0,0,44,Micro,Engineer,Web,76.1,0.043,0.006,21833,Cold
3,0,0,0,0,0,0,0,37,Large,Engineer,FB,47.6,0.010,0.003,22317,Cold
4,0,1,0,0,1,1,1,45,Micro,Procurement,FB,747.9,0.118,0.010,5246,Warm

In [4]:
df.columns

Index(['lien_he', 'tu_van', 'bao_gia', 'demo', 'qtam', 'qd', 'tg', 'age',
       'size', 'role', 'channel', 'web_time', 'frac_react', 'frac_cmt',
       'avg_res', 'target'],
      dtype='object')

In [5]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   lien_he     1000 non-null   int64
 1   tu_van      1000 non-null   int64
 2   bao_gia     1000 non-null   int64
 3   demo        1000 non-null   int64
 4   qtam        1000 non-null   int64
 5   qd          1000 non-null   int64
 6   tg          1000 non-null   int64
 7   age         1000 non-null   int64
 8   size        1000 non-null   object
 9   role        1000 non-null   object
 10  channel     1000 non-null   object
 11  web_time    1000 non-null   float64
 12  frac_react  1000 non-null   float64
 13  frac_cmt    1000 non-null   float64
 14  avg_res     1000 non-null   int64
 15  target      1000 non-null   object
dtypes: float64(3), int64(9), object(4)
memory usage: 125.1+ KB

In [6]:
df_processed = df.copy()

In [7]:

categorical_features  = ['size', 'role', 'channel']
for col in categorical_features :
    print(f"{col}: {df_processed[col].unique()}")

size: ['Micro' 'Medium' 'Large' 'Small' 'Enterprise']
role: ['Manager' 'Marketing' 'Engineer' 'Procurement' 'Director' 'Sales'
 'Assistant' 'Founder' 'CEO']
channel: ['FB' 'Web' 'ZALO']

In [8]:
df_encoded = pd.get_dummies(df_processed, columns=categorical_features , drop_first=True)
df_encoded

,lien_he,tu_van,bao_gia,demo,qtam,qd,tg,age,web_time,frac_react,...,role_CEO,role_Director,role_Engineer,role_Founder,role_Manager,role_Marketing,role_Procurement,role_Sales,channel_Web,channel_ZALO
0,0,0,0,0,1,1,0,52,290.5,0.141,...,False,False,False,False,True,False,False,False,False,False
1,1,1,0,0,1,1,0,52,287.9,0.198,...,False,False,False,False,False,True,False,False,False,False
2,1,0,0,0,1,0,0,44,76.1,0.043,...,False,False,True,False,False,False,False,False,True,False
3,0,0,0,0,0,0,0,37,47.6,0.010,...,False,False,True,False,False,False,False,False,False,False
4,0,1,0,0,1,1,1,45,747.9,0.118,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,0,0,0,1,0,1,40,878.4,0.072,...,False,False,False,False,False,False,True,False,False,True
996,0,1,0,0,1,0,1,43,543.4,0.101,...,False,False,False,False,False,True,False,False,True,False
997,0,1,0,0,1,1,0,56,497.8,0.090,...,False,False,False,False,False,False,True,False,False,True
998,0,0,0,0,0,0,0,45,98.4,0.013,...,False,False,False,False,False,False,False,False,False,False
999,0,1,0,0,1,1,1,55,213.2,0.070,...,False,False,False,False,False,False,False,True,False,True

In [9]:
mapping = {
    "Cold": 1,
    "Warm": 2,
    "Hot": 3
}

df_encoded["target"] = df_encoded["target"].map(mapping)
df_encoded

,lien_he,tu_van,bao_gia,demo,qtam,qd,tg,age,web_time,frac_react,...,role_CEO,role_Director,role_Engineer,role_Founder,role_Manager,role_Marketing,role_Procurement,role_Sales,channel_Web,channel_ZALO
0,0,0,0,0,1,1,0,52,290.5,0.141,...,False,False,False,False,True,False,False,False,False,False
1,1,1,0,0,1,1,0,52,287.9,0.198,...,False,False,False,False,False,True,False,False,False,False
2,1,0,0,0,1,0,0,44,76.1,0.043,...,False,False,True,False,False,False,False,False,True,False
3,0,0,0,0,0,0,0,37,47.6,0.010,...,False,False,True,False,False,False,False,False,False,False
4,0,1,0,0,1,1,1,45,747.9,0.118,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,0,0,0,1,0,1,40,878.4,0.072,...,False,False,False,False,False,False,True,False,False,True
996,0,1,0,0,1,0,1,43,543.4,0.101,...,False,False,False,False,False,True,False,False,True,False
997,0,1,0,0,1,1,0,56,497.8,0.090,...,False,False,False,False,False,False,True,False,False,True
998,0,0,0,0,0,0,0,45,98.4,0.013,...,False,False,False,False,False,False,False,False,False,False
999,0,1,0,0,1,1,1,55,213.2,0.070,...,False,False,False,False,False,False,False,True,False,True

In [10]:

import os

out_dir = '/home/schaffen/Workspace/Project/Lead_classification/data/data/processed'
os.makedirs(out_dir, exist_ok=True)
out_path = os.path.join(out_dir, 'df_processed.csv')

df_encoded.to_csv(out_path, index=False)
print(f"Exported df_processed to {out_path}")

Exported df_processed to /home/schaffen/Workspace/Project/Lead_classification/data/data/processed/df_processed.csv